export const athletes = [
  {
    id: 'kostya',
    name: 'Долгов Константин',
    role: 'Гребец',
    gender: 'Мужской',
    height: 189,
    weight: 87,
    birthYear: 2004,
    sportTitle: 'Мастер спорта России',
    photo: '/img/athletes/photo_5014.png',
    universityId: 'itmo',
    teamId: 'itmo-m8'
  },
  {
    id: 'nastya',
    name: 'Бакланова Анастасия',
    role: 'Гребец',
    gender: 'Женский',
    height: 175,
    weight: 62,
    birthYear: 2004,
    sportTitle: 'Кандидат в мастера спорта',
    photo: '/img/athletes/photo_7510.png',
    universityId: 'itmo',
    teamId: 'itmo-w8'
  },
  {
    id: 'athlete-itmo-3',
    name: 'Александр Морозов',
    role: 'Гребец',
    gender: 'Мужской',
    height: 190,
    weight: 85,
    birthYear: 2002,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'itmo',
    teamId: 'itmo-m8'
  },
  {
    id: 'athlete-itmo-4',
    name: 'Екатерина Соколова',
    role: 'Рулевой',
    gender: 'Женский',
    height: 168,
    weight: 55,
    birthYear: 2003,
    sportTitle: 'Перворазрядник',
    universityId: 'itmo',
    teamId: 'itmo-w8'
  },
  {
    id: 'athlete-itmo-5',
    name: 'Дмитрий Волков',
    role: 'Гребец',
    gender: 'Мужской',
    height: 188,
    weight: 82,
    birthYear: 2002,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'itmo',
    teamId: 'itmo-m8'
  },
  {
    id: 'athlete-itmo-6',
    name: 'Марина Лебедева',
    role: 'Гребец',
    gender: 'Женский',
    height: 175,
    weight: 65,
    birthYear: 2004,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'itmo',
    teamId: 'itmo-w8'
  },
  {
    id: 'athlete-itmo-7',
    name: 'Игорь Кузнецов',
    role: 'Гребец',
    gender: 'Мужской',
    height: 192,
    weight: 90,
    birthYear: 2000,
    sportTitle: 'Мастер спорта России',
    universityId: 'itmo',
    teamId: 'itmo-m8'
  },
  {
    id: 'athlete-itmo-8',
    name: 'Анна Иванова',
    role: 'Гребец',
    gender: 'Женский',
    height: 172,
    weight: 62,
    birthYear: 2001,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'itmo',
    teamId: 'itmo-w8'
  },

    {
    id: 'athlete-dvfu-1',
    name: 'Алексей Иванов',
    role: 'Гребец',
    gender: 'Мужской',
    height: 191,
    weight: 86,
    birthYear: 2002,
    sportTitle: 'Мастер спорта России',
    universityId: 'dvfu',
    teamId: 'dvfu-m8'
  },
  {
    id: 'athlete-dvfu-2',
    name: 'Мария Кузнецова',
    role: 'Гребец',
    gender: 'Женский',
    height: 175,
    weight: 63,
    birthYear: 2003,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'dvfu',
    teamId: 'dvfu-w8'
  },

  {
    id: 'athlete-mgu-1',
    name: 'Иван Иванов',
    role: 'Гребец',
    gender: 'Мужской',
    height: 185,
    weight: 85,
    birthYear: 2000,
    sportTitle: 'Мастер спорта России',
    universityId: 'mgu',
    teamId: 'mgu-m8'
  },
  {
    id: 'athlete-spbgu-1',
    name: 'Мария Петрова',
    role: 'Рулевой',
    gender: 'Женский',
    height: 165,
    weight: 55,
    birthYear: 2002,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'spbgu',
    teamId: 'spbgu-w8'
  },
  {
    id: 'athlete-ngu-1',
    name: 'Алексей Сидоров',
    role: 'Тренер',
    gender: 'Мужской',
    height: 178,
    weight: 78,
    birthYear: 1990,
    sportTitle: 'Мастер спорта России',
    universityId: 'ngu',
    teamId: null
  },
  {
    id: 'athlete-rudn-1',
    name: 'Елена Кузнецова',
    role: 'Гребец',
    gender: 'Женский',
    height: 172,
    weight: 65,
    birthYear: 2001,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'rudn',
    teamId: 'rudn-w8'
  },
  {
    id: 'athlete-mai-1',
    name: 'Дмитрий Васильев',
    role: 'Рулевой',
    gender: 'Мужской',
    height: 170,
    weight: 60,
    birthYear: 2002,
    sportTitle: 'Перворазрядник',
    universityId: 'mai',
    teamId: 'mai-m8'
  },
  {
    id: 'athlete-spbpu-1',
    name: 'Ольга Смирнова',
    role: 'Тренер',
    gender: 'Женский',
    height: 168,
    weight: 58,
    birthYear: 1985,
    sportTitle: 'Мастер спорта России',
    universityId: 'spbpu',
    teamId: null
  },
  {
    id: 'athlete-mfti-1',
    name: 'Сергей Попов',
    role: 'Гребец',
    gender: 'Мужской',
    height: 190,
    weight: 90,
    birthYear: 2000,
    sportTitle: 'Кандидат в мастера спорта',
    universityId: 'mfti',
    teamId: null
  },
  {
    id: 'athlete-mgtu-1',
    name: 'Павел Лебедев',
    role: 'Тренер',
    gender: 'Мужской',
    height: 175,
    weight: 75,
    birthYear: 1988,
    sportTitle: 'Мастер спорта России',
    universityId: 'mgtu',
    teamId: null
  },
  {
    id: 'athlete-voenmeh-1',
    name: 'Никита Новиков',
    role: 'Рулевой',
    gender: 'Мужской',
    height: 168,
    weight: 58,
    birthYear: 2003,
    sportTitle: 'Перворазрядник',
    universityId: 'voenmeh',
    teamId: null
  }
];